// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AccessControl is an autogenerated mock type for the AccessControl type
type AccessControl struct {
	mock.Mock
}

type AccessControl_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessControl) EXPECT() *AccessControl_Expecter {
	return &AccessControl_Expecter{mock: &_m.Mock}
}

// NewAccessControl creates a new instance of AccessControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessControl {
	mock := &AccessControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
