// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DDNS is an autogenerated mock type for the DDNS type
type DDNS struct {
	mock.Mock
}

type DDNS_Expecter struct {
	mock *mock.Mock
}

func (_m *DDNS) EXPECT() *DDNS_Expecter {
	return &DDNS_Expecter{mock: &_m.Mock}
}

// GetRegions provides a mock function with given fields: ctx
func (_m *DDNS) GetRegions(ctx context.Context) {
	_m.Called(ctx)
}

// DDNS_GetRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegions'
type DDNS_GetRegions_Call struct {
	*mock.Call
}

// GetRegions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DDNS_Expecter) GetRegions(ctx interface{}) *DDNS_GetRegions_Call {
	return &DDNS_GetRegions_Call{Call: _e.mock.On("GetRegions", ctx)}
}

func (_c *DDNS_GetRegions_Call) Run(run func(ctx context.Context)) *DDNS_GetRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DDNS_GetRegions_Call) Return() *DDNS_GetRegions_Call {
	_c.Call.Return()
	return _c
}

func (_c *DDNS_GetRegions_Call) RunAndReturn(run func(context.Context)) *DDNS_GetRegions_Call {
	_c.Call.Return(run)
	return _c
}

// NewDDNS creates a new instance of DDNS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDDNS(t interface {
	mock.TestingT
	Cleanup(func())
}) *DDNS {
	mock := &DDNS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
