// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageBroker is an autogenerated mock type for the MessageBroker type
type MessageBroker struct {
	mock.Mock
}

type MessageBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBroker) EXPECT() *MessageBroker_Expecter {
	return &MessageBroker_Expecter{mock: &_m.Mock}
}

// NewMessageBroker creates a new instance of MessageBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBroker {
	mock := &MessageBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
