// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProvisionService is an autogenerated mock type for the ProvisionService type
type ProvisionService struct {
	mock.Mock
}

type ProvisionService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProvisionService) EXPECT() *ProvisionService_Expecter {
	return &ProvisionService_Expecter{mock: &_m.Mock}
}

// NewProvisionService creates a new instance of ProvisionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvisionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProvisionService {
	mock := &ProvisionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
